# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'LW' do

  pod 'AFNetworking','~> 3.1.0', :inhibit_warnings => true
  pod 'SDWebImage','~>4.2.3'
  pod 'SVProgressHUD', '~> 2.2.2'
end
